name: pymake requests

on:
  schedule:
    - cron: '0 3 * * 3' # run at 3 AM UTC every Wednesday
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
jobs:

  pymakeCI-requests:
    name: pymake CI requests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9

      - name: Install python packages
        run: |
          .github/common/install-python.sh

      - name: Run pytest
        run: |
          pytest -v -m requests --durations=0 --cov=pymake --cov-report=xml autotest/

      - name: Run scheduled tests
        if: ${{ github.event_name == 'schedule' }}
        run: |
          pytest -v -m="schedule" --durations=0 --cov=pymake --cov-report=xml autotest/

      - name: Print coverage report before upload
        run: |
          coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./coverage.xml
