name: pymake requests

on:
  schedule:
    - cron: '0 7 * * *' # run at 7 AM UTC every day
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/*.md'
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'docs/*.md'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  pymakeCI-requests:
    name: pymake CI requests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.34.0
          manifest-path: "pixi.toml"

      - name: pixi post-install
        working-directory: pymake
        run: |
          pixi run postinstall

      - name: Run pytest
        run: |
          pixi run autotest-request

      - name: Upload failed test output
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-requests
          path: ./autotest/.failed

      - name: Print coverage report before upload
        run: |
          pixi run coverage-report
  
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./autotest/coverage.xml
