name: pymake requests

on:
  schedule:
    - cron: '0 7 * * *' # run at 7 AM UTC every day
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
jobs:

  pymakeCI-requests:
    name: pymake CI requests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"

      - name: Run pytest
        working-directory: ./autotest
        run: |
          pytest -v -n=auto -m requests --durations=0 --cov=pymake --cov-report=xml

      - name: Run scheduled tests
        if: ${{ github.event_name == 'schedule' }}
        working-directory: ./autotest
        run: |
          pytest -v -m="schedule" --durations=0 --cov=pymake --cov-report=xml

      - name: Print coverage report before upload
        working-directory: ./autotest
        run: |
          coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./autotest/coverage.xml
